kind: "BuildConfig"
apiVersion: "build.openshift.io/v1"
metadata:
  name: ran-hw-operator
  namespace: ran-operator
spec:
  runPolicy: "Serial"
  source:
    git:
      uri: https://github.com/bsuro10/operator-sdk-workshop
  strategy:
    sourceStrategy:
      from:
        kind: "DockerImage"
        name: "docker.io/dimssss/golang-s2i:0.5"
  output:
    to:
      kind: "DockerImage"
      name: "docker.io/bsuro10/ran-operator:latest"
    pushSecret:
      name: 4c908bfb-1418-450d-a7f8-b49174655083
