// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RanHelloWorld) DeepCopyInto(out *RanHelloWorld) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RanHelloWorld.
func (in *RanHelloWorld) DeepCopy() *RanHelloWorld {
	if in == nil {
		return nil
	}
	out := new(RanHelloWorld)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RanHelloWorld) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RanHelloWorldList) DeepCopyInto(out *RanHelloWorldList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RanHelloWorld, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RanHelloWorldList.
func (in *RanHelloWorldList) DeepCopy() *RanHelloWorldList {
	if in == nil {
		return nil
	}
	out := new(RanHelloWorldList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RanHelloWorldList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RanHelloWorldSpec) DeepCopyInto(out *RanHelloWorldSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RanHelloWorldSpec.
func (in *RanHelloWorldSpec) DeepCopy() *RanHelloWorldSpec {
	if in == nil {
		return nil
	}
	out := new(RanHelloWorldSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RanHelloWorldStatus) DeepCopyInto(out *RanHelloWorldStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RanHelloWorldStatus.
func (in *RanHelloWorldStatus) DeepCopy() *RanHelloWorldStatus {
	if in == nil {
		return nil
	}
	out := new(RanHelloWorldStatus)
	in.DeepCopyInto(out)
	return out
}
